authentications/urls.py
from django.urls import path
from . import views

app_name ='authentications'

urlpatterns = [
   
    path('register_user', views.register_user, name ='register_user'),
    path('loggin', views.loggin, name ='loggin'),
    path('logout', views.logout, name ='logout'),
    
]

hotel_booking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotelapp.urls')),
    # path('', include('myapp.urls')),
    path('authentications/', include('authentications.urls')),
    
    # path("djangoflutterwave/", include("djangoflutterwave.urls", namespace="djangoflutterwave"))
    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotelapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
   
    path('', views.home, name ='home'),
    path('booking_room/<int:roomtype_id>/', views.booking_room, name ='booking_room'),
    path('available_rooms/<int:room_id>/', views.available_rooms, name ='available_rooms'),
    path('booked_room/', views.booked_room, name ='booked_room'),
    path('room_availability/<int:roomtype_id>/', views.room_availability, name ='room_availability'),
    path('all_categories/<int:roomtype_id>/', views.all_categories, name ='all_categories'),
    path('cancel_order/<int:booked_id>/', views.cancel_order, name ='cancel_order'),
    path('paydetail/<int:room_id>/', views.paydetail, name='paydetail'),
    path('payment/<int:availability_id>/', views.payment, name='payment'),
    path('payindividually/', views.payindividually, name='payindividually'),
    path('review_room/<int:booking_id>/', views.review_room, name='review_room'),
    path('delete_review/<int:review_id>/', views.delete_review, name='delete_review'),
    
]

hotelapp/forms.py
from django import forms
from hotelapp.models import Booking, Room, Hotel,Review
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field


class MyDateInput(forms.widgets.DateInput):
    input_type = 'date'

class BookingForm(forms.Form):
    hotel = forms.ModelChoiceField(queryset=Hotel.objects.all())
    check_in = forms.DateField(widget=MyDateInput())
    check_out = forms.DateField(widget=MyDateInput())

class ReviewForm(forms.ModelForm):
    
    class Meta:
        model =Review
        fields = ['hotel', 'rating', 'review_text', 'images']
        
    def clean(self):
        cleaned_data = super().clean()
        review_text = cleaned_data.get('review_text')
        if len(review_text) >= 1000:
            raise forms.ValidationError('Review text must not be more than 1000 words')
        return cleaned_data

hotelapp/views.py
import math
from random import random
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse
from hotelapp.models import RoomType, Zumalogo, Review,BookingItem, Booking, Room, Payment, Availability
from django.contrib import messages
from hotelapp.forms import BookingForm, ReviewForm
from django.db.models import Q
from datetime import datetime

from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import requests
import random
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from hotelapp.availability import is_room_available,find_available_room

from django.db.models import Avg


# Create your views here.
def home(request):
    reviews= Review.objects.all()
    type_of_room = RoomType.objects.all()
    logo = Zumalogo.objects.first()
    
    roomtypes = RoomType.objects.annotate(avg_rating=Avg('booking__review__rating')).order_by('-avg_rating')
   
    highest_avg_rating = 0  # Initialize with a low value
    trending_room_type=None
    for roomtype in roomtypes:
        if roomtype.avg_rating is not None and roomtype.avg_rating > highest_avg_rating:
            highest_avg_rating = roomtype.avg_rating
            trending_room_type = roomtype
    
    context ={
        'trending_room_type': trending_room_type,
        'roomtypes':type_of_room,
        'logos':logo,
        'reviews':reviews,
    }
    return render(request, 'hotelapp/home.html', context)

def all_categories(request, roomtype_id):
    room = Room.objects.get(id=roomtype_id)
    type_of_rooms = RoomType.objects.get(id=room.id)
    get_all_room_category = type_of_rooms.room_set.all()
    
    context = {
        
        'category':get_all_room_category,
        
    }
    
    return render(request, 'hotelapp/all_categories.html', context)


def room_availability(request, roomtype_id):
    room =None
    type_of_rooms=None
    try:
        room = Room.objects.get(id=roomtype_id)
        type_of_rooms = RoomType.objects.get(id=room.id)
    except RoomType.DoesNotExist and Room.DoesNotExist:
        messages.info(request, 'No room added yet to this category')
       
    # get_all_room_category = type_of_rooms.room_set.all()
    rooms = Room.objects.filter(room_type=type_of_rooms, is_available=True)#.exclude(
                #booking__check_out__gte=check_in,  # Exclude booked rooms for check_out date >= check_in date
               # booking__check_in__lte=check_out,   # Exclude booked rooms for check_in date <= check_out date
           # )
    # room_field = Room.objects.filter(room_type=type_of_rooms)
    
    type_of_room = RoomType.objects.all()
    logo = Zumalogo.objects.first()
    
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            check_in = form.cleaned_data['check_in']
            check_out = form.cleaned_data['check_out']
            
            existing_booking = Booking.objects.filter(
                Q(room__in=rooms) &
                (Q(check_in__range=(check_in, check_out)) | Q(check_out__range=(check_in, check_out)))
            )
            if existing_booking.exists():
                messages.info(request, 'Sorry! This is already booke within the range of your check in and check out. Try another date')
                return redirect('room_availability', roomtype_id = roomtype_id)
            else:
               
                messages.info(request, 'Your room is available. Proceed with payment.')
                return redirect('booking_room', roomtype_id=roomtype_id )
                
    else:
        form = BookingForm()
      

    context = {
        'form': form,
        'room_type': room,
        'room': rooms,
        'rooms':room,
        # 'category':get_all_room_category,
        'type_of_rooms':type_of_rooms,
        'roomtypes':type_of_room,
        'logos':logo
    }
    
    return render(request, 'hotelapp/availability.html', context)


@login_required(login_url ='authentications:loggin')
def booking_room(request, roomtype_id):
    logo = Zumalogo.objects.first()
    room_type = RoomType.objects.get(id=roomtype_id)
    rooms = Room.objects.filter(room_type=room_type, is_available=True)

    if not rooms.exists():
        messages.error(request, 'No rooms are available for booking. Please choose different dates.')
        return redirect('available_rooms', roomtype_id=room_type.id)

    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            check_in = form.cleaned_data['check_in']
            check_out = form.cleaned_data['check_out']

            existing_booking = Availability.objects.filter(
                room_type=room_type,
                check_in__lt=check_out,
                check_out__gt=check_in
            )
            for room in rooms:
                if is_room_available(room =room, check_in=check_in, check_out=check_out):
                    booked_room_numbers = set()
                    for booking in existing_booking:
                        booked_room_numbers.update(room.room_number for room in booking.booked_rooms.all())
                                
                    available_rooms = rooms.exclude(room_number__in=booked_room_numbers)
                    if available_rooms.exists():
                        available_room = available_rooms.first()
                        booking = Availability.objects.create(
                            user=request.user,
                            hotel=available_room.hotel,
                            room_type=room_type,
                            check_in=check_in,
                            check_out=check_out,
                            total_price=room_type.price
                        )
                        booking.booked_rooms.add(available_room)

                        messages.info(request, 'An available room has been booked for you. Proceed with payment.')
                        return redirect('payindividually')
                    else:
                        messages.error(request, 'No rooms are available for booking.')
                        return redirect('available_rooms', roomtype_id=room_type.id)
                else:
                    messages.info(request, 'Room is booked within the date you choose. Select another date please!')
                    return redirect('booking_room', roomtype_id=room_type.id)

    else:
        form = BookingForm()

    context = {
        'form': form,
        'room_type': room_type,
        'room': rooms,
        'category': room_type.room_set.all(),
        'type_of_rooms': room_type,
        'logos': logo,
    }

    return render(request, 'hotelapp/booking_page.html', context)



def available_rooms(request, room_id):
    room = Room.objects.get(id=room_id)
    available_room = Room.objects.filter(room_type=room.room_type, is_available=True)
    
    context = {
        'availability':available_room,
    }
    return render(request, 'hotelapp/error_page.html', context)

@login_required(login_url='authentications:loggin')
def payindividually(request):
    user = request.user
    
    all_booked_rooms = Availability.objects.filter(user =user)
    type_of_room = RoomType.objects.all()
    logo = Zumalogo.objects.first()
    bookings = Booking.objects.filter(user=user)
    
    get_first_item_that_meet_the_criteria = all_booked_rooms.first()
    
    booking_items = BookingItem.objects.filter(availability__in=all_booked_rooms)
    
    total_price=None
    for book in all_booked_rooms:
        checkin = book.check_in
        checkout = book.check_out
        number_of_days = (checkout - checkin).days
        total_price = book.room_type.price * number_of_days
        
        book.number_of_days = number_of_days
        book.total_price = total_price
        
    for booking_item in booking_items:
        checkin = booking_item.availability.check_in
        checkout = booking_item.availability.check_out
        number_of_days = (checkout - checkin).days
        booking_item.number_of_days = number_of_days
        
    context = {
        'all_booked_rooms':all_booked_rooms,
        'logos':logo, 
        'roomtypes':type_of_room,
        'total': total_price,
        'bookings':bookings,
        'items':booking_items,
        'days':number_of_days
    }
    return render(request, 'hotelapp/all_booked.html', context)

@login_required(login_url='authentications:loggin')
def paydetail(request, room_id):
    type_of_room = RoomType.objects.all()
    logo = Zumalogo.objects.first()
        
    details = Availability.objects.get(id=room_id)
    # booking = Booking.objects.get(payment__charge_id = details)
    
    
    checkin = details.check_in
    checkout = details.check_out
    number_of_days = (checkout - checkin).days
    total_price = details.room_type.price * number_of_days
        
    context = {
        'room':details,
        'number_of_days':number_of_days, 
        'roomtypes':type_of_room,
        'logos':logo, 
        'total_price':total_price,
        # 'booking':booking     
    }
    return render(request, 'hotelapp/book_detail.html', context)
    
@login_required(login_url='authentications:loggin')    
def booked_room(request):
    user = request.user
    room_booked = Availability.objects.filter(user=user)
    

    total_amount = 0
    # room_ids = [room.room.id for room in room_booked]
    for room in room_booked:
        check_in = room.check_in
        check_out = room.check_out
        num_of_days = (check_out - check_in).days
        total_amount += num_of_days * room.total_price  # Add the current room's total amount to the overall total

        room.num_of_days = num_of_days
        room.total_amount = total_amount

    context = {
        'booked': room_booked,
        'total': total_amount,  # Use the total_amount calculated in the loop
    }

    return render(request, 'hotelapp/success_page.html', context)

hotelapp/templates/hotelapp/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>Hotel Booking System{% block title %}{% endblock %}</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="The River template project">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css"> -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="{% static 'hotelapp/style.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700|Pacifico&display=swap" rel="stylesheet">




<!-- <script>
	function showDatePicker(inputId) {
	  $('#' + inputId).datepicker('show');
	}
  
	$(document).ready(function() {
	  $('#check-in-date').datepicker();
	  $('#check-out-date').datepicker();
	});
  </script> -->
  

<style>
    body
{
	font-family: 'Raleway', sans-serif;
	font-size: 14px;
	font-weight: 400;
	background: rgb(213, 200, 200);
	color: #a5a5a5;
    height: 100vh;
}

/* your account nav link */
.account-icon {
	width: 20px;
	height: 20px;
	margin-right: 10px;
  }
  
  .dropdown-icon {
	width: 16px;
	height: 16px;
	margin-right: 10px;
  }
/* end of your account   */

/* nav bar control */
.navbar-nav .nav-item .nav-link:hover {
  color: white !important; 
}



/* footer */
.footer
{
	background: #ffffff;
	padding-top: 81px;
}
.footer_content
{
	padding-bottom: 52px;
}
.footer_logo
{
	display: inline-block;
	text-align: center;
	margin-left: auto;
	margin-right: auto;
}
.footer_logo > div:first-of-type
{
	width: 235px;
	height: 74px;
	border: solid 3px #393939;
	font-size: 43.32px;
	font-weight: 600;
	color: #393939;
	line-height: 68px;
}
.footer_logo > div:last-of-type
{
	font-size: 16px;
	font-weight: 600;
	color: #393939;
	line-height: 0.75;
	margin-top: 15px;
}
.footer_logo a
{
	display: block;
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	z-index: 1;
}
.footer_row
{
	margin-top: 74px;
}
.footer_title
{
	font-size: 18px;
	font-weight: 700;
	color: #393939;
	line-height: 1.2;
}
.footer_list
{
	margin-top: 9px;
}
.footer_list ul li
{
	font-size: 15px;
	font-weight: 500;
	color: #6d6d6d;
	line-height: 2;
}
.newsletter_container
{
	margin-top: 8px;
}
.newsletter_form
{
	display: block;
	position: relative;
}
.newsletter_input
{
	width: 100%;
	height: 64px;
	background: #ffffff;
	border: none;
	border-bottom: solid 2px #393939;
	outline: none;
	font-size: 15px;
	font-weight: 600;
	color: #393939;
}
.newsletter_input::-webkit-input-placeholder
{
	font-size: 15px !important;
	font-weight: 500 !important;
	color: #6d6d6d !important;
}
.newsletter_input:-moz-placeholder
{
	font-size: 15px !important;
	font-weight: 500 !important;
	color: #6d6d6d !important;
}
.newsletter_input::-moz-placeholder
{
	font-size: 15px !important;
	font-weight: 500 !important;
	color: #6d6d6d !important;
} 
.newsletter_input:-ms-input-placeholder
{ 
	font-size: 15px !important;
	font-weight: 500 !important;
	color: #6d6d6d !important;
}
.newsletter_input::input-placeholder
{
	font-size: 15px !important;
	font-weight: 500 !important;
	color: #6d6d6d !important;
}
.newsletter_button
{
	width: 152px;
	height: 54px;
	background: #ffa37b;
	margin-top: 23px;
	border: none;
	outline: none;
	cursor: pointer;
	font-size: 14px;
	font-weight: 600;
	color: #ffffff;
}
.certificates
{
	padding-left: 12px;
	padding-top: 10px;
}
.cert
{
	margin-bottom: 30px;
}
.copyright
{
	width: 100%;
	height: 33px;
	background: #ffffff;
	text-align: center;
	line-height: 33px;
	font-size: 15px;
	font-weight: 500;
	color: #6d6d6d;
}

/* booking form */

    .formcard {
      background-color: orange;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    }
  
    .booking-form {
      margin-bottom: 20px;
    }
  
    .booking-form input,
    .booking-form select {
      width: 100%;
      padding: 10px;
      margin-bottom: 10px;
      border: 1px solid #ccc;
      border-radius: 4px;
    }
  
    .booking-form button {
      width: 100%;
      padding: 10px;
      background-color: #4CAF50;
      color: white;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }
  
    /* Customized calendar styles */
    .advanced-calendar {
      width: 100%;
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 4px;
      background-color: white;
      position: relative;
    }
  
    .advanced-calendar input {
      width: 100%;
      border: none;
      background-color: transparent;
      cursor: pointer;
    }
  
    .advanced-calendar .calendar-icon {
      position: absolute;
      top: 50%;
      right: 10px;
      transform: translateY(-50%);
      pointer-events: none;
    }

    /* booked table */
    .booking-table {
      margin-top: 20px;
    }
  
    .booking-table th, .booking-table td {
      padding: 10px;
      text-align: center;
    }
  
    .booking-table th {
      background-color: #f2f2f2;
      font-weight: bold;
    }
  
    .booking-table tr:nth-child(even) {
      background-color: #f9f9f9;
    }
  
    .booking-table tr:hover {
      background-color: #e8e8e8;
    }
  
    .booking-button {
      margin-top: 20px;
    }
    /* booked price */
  .decorate-price{
    opacity: 0.4;
    margin: 5px;
    border-radius: 15%;
    border-style: dotted;
    border-width: 5px;
    
    
        }
        
  .get-body{
      font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
      color: rgb(232, 146, 146);
      font-weight: bold;
      font-size: 1.5rem;
            
        }
  /* homepaage styling */
  .overlay {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5); 
        z-index: 2;
    }
    .image-hover-effect {
        transition: transform 0.3s, box-shadow 0.3s;
    }

    .image-hover-effect:hover {
        transform: scale(1.05);
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
    }
</style>
</head>
<body>
<!-- Menu -->
<nav class="navbar navbar-expand-lg navbar-light p-4" style="background-color: #2b9e82;">
  <a class="navbar-brand" href="#">
      <img src="{{ logos.logo.url }}" alt="Zuma Resort" class="logo-image" style="max-width: 150px; height: auto;">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto" style="font-size: 1.2rem;">
          <li class="nav-item active">
              <a class="nav-link text-white" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
              <a class="nav-link text-white" href="#">All Resorts</a>
          </li>
          <li class="nav-item">
              <a class="nav-link text-white" href="#">Facilities</a>
          </li>
          <li class="nav-item">
              <a class="nav-link text-white" href="#">Info/Prices</a>
          </li>
          <li class="nav-item">
              <a class="nav-link text-white" href="#">House Rules</a>
          </li>
          
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <img src="{{ user.photo.url }}" alt="Your Account" class="account-icon rounded-circle mr-2" style="max-width: 80px; height: auto;">
                  Hi, {{ user.username }}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">
                      <i class="fas fa-user-cog mr-2"></i> Account Settings
                  </a>
                  <a class="dropdown-item" href="#">
                      <i class="fas fa-shopping-cart mr-2"></i> Orders
                  </a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'authentications:logout' %}">
                      <i class="fas fa-sign-out-alt mr-2"></i> Sign Out
                  </a>
              </div>
          </li>
          {% else %}
          <li class="nav-item">
              <a class="nav-link btn btn-outline-light mx-2" href="{% url 'authentications:loggin' %}">Sign in</a>
          </li>
          <li class="nav-item">
              <a class="nav-link btn btn-light mx-2" href="{% url 'authentications:register_user' %}">Register</a>
          </li>
          {% endif %}
      </ul>
  </div>
</nav>
{% for message in messages %}
<div class="alert alert-danger fade-in alert-dismissible text-center">
  <strong>Notification!</strong> {{ message }}
</div>
{% endfor %}

{% block content %}
{% endblock %}


<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

hotelapp/templates/hotelapp/base/footer.html
<footer class="footer">
    <div class="footer_content">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="footer_logo_container text-center">
                        <div class="footer_logo">
                            <a href="#"></a>
                            <div>The River</div>
                            <div>since 1945</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row footer_row">
                
                <!-- Address -->
                <div class="col-lg-3">
                    <div class="footer_title">Our Address</div>
                    <div class="footer_list">
                        <ul>
                            <li>Beach Str. 345</li>
                            <li>67559 Miami</li>
                            <li>USA</li>
                        </ul>
                    </div>
                </div>

                <!-- Reservations -->
                <div class="col-lg-3">
                    <div class="footer_title">Reservations</div>
                    <div class="footer_list">
                        <ul>
                            <li>Tel: 345 5667 889</li>
                            <li>Fax; 6783 4567 889</li>
                            <li>reservations@hotelriver.com</li>
                        </ul>
                    </div>
                </div>

                <!-- Newsletter -->
                <div class="col-lg-3">
                    <div class="footer_title">Newsletter</div>
                    <div class="newsletter_container">
                        <form action="#" class="newsletter_form" id="newsletter_form">
                            <input type="email" class="newsletter_input" placeholder="Your email address" required="required">
                            <button class="newsletter_button">Subscribe</button>
                        </form>
                    </div>
                </div>

                <!-- Footer images -->
                <div class="col-lg-3">
                    <div class="certificates d-flex flex-row align-items-start justify-content-lg-between justify-content-start flex-lg-nowrap flex-wrap">
                        <div class="cert"><img src="images/cert_1.png" alt=""></div>
                        <div class="cert"><img src="images/cert_2.png" alt=""></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright">
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</div>
</footer>
</div>